### ISSUE TITLE
Explicitly disallow a non-empty text node in a list node

### ISSUE THREAD

**Issue by m1kit** [spdx/LicenseListPublisher#104]
See: https://github.com/m1kit/license-matcher-python/issues/1#issuecomment-851017637

**Comment by m1kit** [comment]
The list nodes in the current license list contains only text nodes consisting of spaces. Do we have to insert such spaces? Or just ignore them?

**Comment by goneall** [comment]
> The list nodes in the current license list contains only text nodes consisting of spaces. Do we have to insert such spaces? Or just ignore them?

Since this is in a template, it probably doesn't matter since the matching algorithm ignores white space when comparing.  I'm leaning towards including the spaces since they were in the original XML.

**Comment by goneall** [comment]
Resolved with PR #116
