### ISSUE TITLE
Create an index page for the archived license lists

### ISSUE THREAD

**Issue by goneall** [spdx/LicenseListPublisher#11]
Per suggestion from @pombredanne on the SPDX legal mailing list

1. create a page that has links to the older versions of the LL page 
2. link this "archives" page from the current LL version 
3. link the previous version too 
4. as a bonus possibly link the preview next when  this is published and mostly ready before we switch over to final

These links could be on the same line as the line that says:

"Version: 3.0 28 December 2017" or using an ISO
 
Something like :

Current Version: 3.0 28 December 2017  - (previous version, versions archive, next version preview, )

NOTE: following suggestions on the email suggest using an ISO 8601 to express time.
See https://en.wikipedia.org/wiki/ISO_8601

Version: 3.0 published on 2017-12-28

Version: 3.0 of 2017-12-28

**Comment by goneall** [comment]
From @wking 

It would also be nice to be able to link to [1] in a way that will survive 3.1 getting cut.

About the URL template itself, I'd rather not repeat “archive”, and “archive” no longer feels quite right once you have an entry for the current release.  I also think the /licenses/ prefix already covers “ll” (which I'm guessing is for “License List”).  Wouldn't it be sufficient to use:

  https://spdx.org/licenses/v3.0/

or at most:

  https://spdx.org/licenses/release/v3.0/

Cheers,
Trevor

[1]: https://spdx.org/licenses/archive/archived_ll_v3.0/

**Comment by wking** [comment]
Cross-linking [the list thread][0].

> 1. create a page that has links to the older versions of the LL page
> 2. link this "archives" page from the current LL version

I'd rather keep this outside of `LicenseListPublisher`.  For example, see [my mock-up][1], which adds a landing page linking to the various releases.  There is no cross-linking between the releases themselves.

[JSON Schema's specifications page][2] takes a similar approach, outlining their current releases and then linking to [a separate page][3] with links to past and current releases.  This reduces clutter on the initial page if you have a lot to say there and want to de-emphasise the older releases.

RFCs get updated with *forward* links (“Obsoleted by” in the header, e.g. [here][4]), to gently nudge folks from obsolete releases forward into the present.  I'm fine with that, but don't think it needs to be part of the LicenseListPublisher process (you can add the forward links manually in post-production).

[0]: https://lists.spdx.org/pipermail/spdx-legal/2018-March/002517.html
[1]: https://wking.github.io/license-list-data/
[2]: http://json-schema.org/specification.html
[3]: http://json-schema.org/specification-links.html
[4]: https://tools.ietf.org/html/rfc2616

**Comment by goneall** [comment]
Since you can now access previous versions of the website and license list easily on Github license-list-data, I'm closing this (rather old) issue.
