### ISSUE TITLE
Clarify that the license identifier is deprecated

### ISSUE THREAD

**Issue by jgneff** [spdx/LicenseListPublisher#127]
Clarify that the license identifier, and not the license itself, is deprecated. The current text is confusing.

The Ubuntu Software app links directly from the SPDX license identifier of an application to the page for the identifier on the SPDX website. The text on the page of a deprecated license identifier could lead one to believe that the license itself is deprecated in favor of some other license, yet the text actually means that just the identifier is deprecated.

For example, see the [GNU General Public License v2.0 w/Classpath exception](https://spdx.org/licenses/GPL-2.0-with-classpath-exception) which states, "This license has been deprecated since license list version 2.0rc2."

**Comment by jgneff** [comment]
This problem is similar to [Issue #22](https://github.com/spdx/LicenseListPublisher/issues/22). I'll submit a pull request shortly.

**Comment by jgneff** [comment]
Note that a bug in the Ubuntu Software application prevents Snap and Debian packages from using the new non-deprecated license expressions instead of the old deprecated license identifiers. The bug is "[snap-store says an app is proprietary while it's free](https://bugs.launchpad.net/snap-store-desktop/+bug/1878924)." For more details, see [my latest comment](https://bugs.launchpad.net/snap-store-desktop/+bug/1878924/comments/7) on the bug report.

**Comment by jgneff** [comment]
**Note:** I'm just waiting for the actual text [on the Web page](https://spdx.org/licenses/GPL-2.0-with-classpath-exception) to show the fix before closing this issue.

**Comment by jgneff** [comment]
Is there a way to regenerate the website so that this fix takes effect? The fix was merged a couple months ago, but the webiste still has the old text. See [GNU General Public License v2.0 w/Classpath exception](https://spdx.org/licenses/GPL-2.0-with-classpath-exception). Let me know if there's something I can do to help.

**Comment by goneall** [comment]
@jgneff I'll need to produce a release of the LicenseListPublisher which will get picked up in the next release of the license list.  I'm currently traveling with very limited network bandwidth - once I'm back on dry land in 3 or 4 days, I'll publish the release.

**Comment by goneall** [comment]
@jgneff I just created a new release and a PR to update the license list publisher version for the next release of the SPDX license list (https://github.com/spdx/license-list-XML/pull/1440).  It should get updated on the next regular release.

cc: @swinslow

**Comment by swinslow** [comment]
Thank you @goneall and @jgneff -- this is now merged in license-list-XML, and will be updated on the website as of the 3.17 release (which is targeted for the end of April).
