### ISSUE TITLE
KICAD-exception not licenses

### ISSUE THREAD

**Issue by ecki** [spdx/LicenseListPublisher#133]
In the (JSON) license.json file I [see](https://github.com/spdx/license-list-data/blob/7bd3f753d70c065dbf270598cc9736169b29835d/json/licenses.json#L105) entry named like KiCad-libraries-exception and when I look at the detailed file it is not a full license only an exception. Should probably be moved to the exceptions.json?

also should there be an link to the base license an exception normally applies to? (Not all exceptions have such an unstructured comment)

also the exceptions.json list has not the same fully qualified URLs as reference and details page like the license list has. And both miss relative links to the details file.

**Comment by ecki** [comment]
I think the problem is in the xml file, I opened a issue for it here: https://github.com/spdx/license-list-XML/issues/1520

**Comment by goneall** [comment]
Indeed - this is an issue with the XML.  @ecki good catch!  I just created a PR to fix - I'm going to close this issue.
