### ISSUE TITLE
How should we cite SPDX work?

### ISSUE THREAD

**Issue by javiquinte** [spdx/LicenseListPublisher#134]
Dear SPDX Team,

I'm working on a software package that uses the list of licenses in JSON format from your Github repository.
Is there any particular reference or citation I should introduce in the code? Or in any other place?

Thanks in advance for your support and for the great work.

P.S.: Sorry for posting this here, but the two EMail addresses to contact you are rejecting my messages claiming that it is spam.

**Comment by goneall** [comment]
@javiquinte Glad to hear you're finding the license data useful.

There is no citation required to use the license list data itself from the license-list-data repo.  A related question on the license for the license meta data has come up a few times, and the legal team has decided that a license wasn't needed (reference [this comment](https://github.com/spdx/license-list-XML/issues/648#issuecomment-397373891)).  

If you use any of the library code, just include the Apache license notice as required by the license.

**Comment by javiquinte** [comment]
Thanks a lot, @goneall !
