### ISSUE TITLE
license text inconsistency

### ISSUE THREAD

**Issue by OlshaMB** [spdx/LicenseListPublisher#140]
I am writing a cli to install license in the current dir in rust.
And I have problem using https://github.com/spdx/license-list-data because in the folder /text there are two formats: 
1. `Copyright (C) YEAR by AUTHOR EMAIL` in 0BSD.txt
2. `Copyright (c) <year> <copyright holders>` in MIT.txt
3. And maybe there is another one, I haven't checked them all
And I need consistency to be able to format/replace with actual year and author.

**P. S.**
And also saw /template dir but there I need to parse some custom format, but I am not ready to write parser for that.
Also I won't use xml format

**Comment by goneall** [comment]
@OlshaMB The files in the /text folder are verbatim license text without any formatting.  I don't know of any standard way of marking the year within the copyright across all licenses.  The format in the /template folder only specifies which text is optional for license matching purposes - so it wouldn't help (even if you wanted to write a parser).  The license-list-XML format does have tags for title and copyright text, but does not have a tag specific to the date.

**Comment by goneall** [comment]
I'm going to close this issue as it doesn't apply to this library.
