### ISSUE TITLE
Sort JSON by some stable identifier

### ISSUE THREAD

**Issue by JakeWharton** [spdx/LicenseListPublisher#146]
We embed the JSON in our tool and regularly update it when it changes. The JSON file seems to randomly change order on each update making its diff unreviewable. We don't actually want to review the contents, but with a stable sort we would at least be able to visually sanity check that the changes are as expected.

**Comment by goneall** [comment]
I'm planning on a new release of the LicenseListPublisher before the next license list release - if it's not to hard, I'll include a fix for this.

**Comment by JakeWharton** [comment]
Thanks!
