### ISSUE TITLE
Abstyles' Copyright is not provided as variable

### ISSUE THREAD

**Issue by TimothyGillespie** [spdx/LicenseListPublisher#151]
The standard template for the Abstyles license contains a copyright header that is not marked as a variable. It seems unintentional.

https://github.com/spdx/license-list-data/blob/af10ab11e58cb61d06b57f6eaf3df31497783d0a/json/details/Abstyles.json#L4

Edit: I also noticed the same in the AGPL. If that is unintended, I'd be happy to point these out or fix them directly if I figure out how this repository works.

I also just found https://github.com/spdx/license-list-XML. I suppose that would have been the better repository for this?

**Comment by goneall** [comment]
> I also just found https://github.com/spdx/license-list-XML. I suppose that would have been the better repository for this?

Yes - that is the repo where the markups for the variable text is made.  You can create a PR to fix those by adding `<alt` tags around the copyright text which should be variable.
