### ISSUE TITLE
Show regexp in HTML output for replacable text

### ISSUE THREAD

**Issue by goneall** [spdx/LicenseListPublisher#17]
Submitted by @wking and moved from https://github.com/spdx/tools/issues/120

[`formatReplaceabledHTML`][1] currently sets `class="replacable-license-text"`.  I think we should also set `title="match-regexp"` or something so users can mouse over (if they have a mouse) to see the replacement regexp.  Raw regexps aren't the greatest UX, but [that's what we've been using so far][2], and I can't think of anything better.

Spun off from [here][3].

[1]: https://github.com/spdx/tools/blob/d8ef31bf86099dd700555e9d173719a6478b2c46/src/org/spdx/licenseTemplate/HtmlTemplateOutputHandler.java#L93-L113
[2]: https://github.com/spdx/spdx-spec/blame/cfa1b9d08903befdf03e669da6472707b7b60cb9/chapters/appendix-II-license-matching-guidelines-and-templates.md#L28
[3]: https://github.com/spdx/license-list-XML/pull/489#discussion_r153291051

**Comment by goneall** [comment]
Please refer to the original closed issue for the entire conversation: https://github.com/spdx/tools/issues/120

From @wking 

I've mocked something up at [1], which is primarily using CSS with a
<span> placeholder wherever you want the icon.  That ensures the icon
is not going to be copy/pasted from a rendering of the HTML.  I've
used ☿ for the icon, but I didn't hunt around too hard.  Anything that
gets “this might change” across and won't be mistaken for the license
text itself would work.

[1]: http://tremily.us/var-match.html

**Comment by goneall** [comment]
I'm going to wait one more release of the license list (version 3.2) to give @jlovejoy a chance to review and comment on the UI

**Comment by goneall** [comment]
I haven't heard from @jlovejoy on this, so I'm closing the issue.

**Comment by jlovejoy** [comment]
sorry @goneall - this is old and re-reading it now, I'm not even sure what it was proposing!

**Comment by goneall** [comment]
> sorry @goneall - this is old and re-reading it now, I'm not even sure what it was proposing!

No worries - it was proposing we add a feather where you click or hover over the replaceable text and it will show you the regular expression.  I think there was only one person requesting the feature, so we should be fine just closing it.
