### ISSUE TITLE
Formatting issue with standardLicenseHeader in Apache-2.0.json

### ISSUE THREAD

**Issue by nandita-v** [spdx/LicenseListPublisher#172]
It looks like there is a formatting issue with the `standardLicenseHeader` field in the [Apache-2.0.json](https://github.com/spdx/license-list-data/blob/main/json/details/Apache-2.0.json#L10) file. The `standardLicenseHeader` field has two '\n' between every line in the header which seems inconsistent with the output from the html file and the [text file.](https://github.com/spdx/license-list-data/blob/main/text/Apache-2.0.txt) Attaching screenshots below: 

**Expected standard license header:**
<img width="520" alt="Correct Output" src="https://github.com/spdx/license-list-XML/assets/139924575/8bfef402-e3ae-46c3-a173-e0989b23e47c">

**Standard license header from the JSON file:** 
<img width="506" alt="Incorrect Output" src="https://github.com/spdx/license-list-XML/assets/139924575/dab69a0f-d545-4980-ae62-92867152ae04">

**Comment by mochaaP** [comment]
This also broke `Apache-2.0.json`'s `standardLicenseHeaderTemplate` field.

---

<details>

Blocking: <https://todo.sr.ht/~reggie/licenses.nvim/1>

</details>

**Comment by goneall** [comment]
@mochaaP Thanks for pointing this out - from looking at the downstream use - it looks like you have a workaround for now.  If this is blocking any project please let me know and I'll bump up the priority for a fix.  Of course, any help from other volunteers would be most welcome.
