### ISSUE TITLE
Consistent header/value for license-list “Text” column

### ISSUE THREAD

**Issue by goneall** [spdx/LicenseListPublisher#18]
Submitted by @wking 

And as a very minor nit for `resources/htmlTemplate/TocHTMLTemplate.html`, it's a bit strange to have a “Text” header on a column where all the values are “License Text”.  If “Text” is sufficient, why not use that everywhere?  If “Text” is not sufficient, why not use “License Text” in the header?  I'm also fine dropping this column entirely, because the license name already links to the per-license page, and few of our licenses have so many notes and such that that the text is hard to find there ;).

**Comment by goneall** [comment]
@jlovejoy I'll leave the TOC format questions to you - let us know if you want any modifications as suggested by @wking   The template can also be updated through a PR: https://github.com/spdx/tools/blob/722d95784f55b3923ed0428c4abf2fc915eb2b2e/resources/htmlTemplate/TocHTMLTemplate.html#L162

**Comment by goneall** [comment]
Moved from https://github.com/spdx/tools/issues/118

**Comment by goneall** [comment]
@jlovejoy @swinslow I'll leave the formatting questions to the legal team - please let me know if you'd like this change to be made in the template.  If not, I'd like to close this very old issue.

**Comment by swinslow** [comment]
Coincidentally I was thinking about exactly this thing yesterday (though I hadn't seen this issue before). I would be in favor of just dropping the column that says "License Text" in the TOC. I think in most cases folks will be clicking on the license name column anyway, and so I don't think the "License Text" row necessarily adds anything.

**Comment by goneall** [comment]
PR #85  removes the Text column.  @jlovejoy @swinslow if there are no objections, I'll merge the PR for the next license list release.

Below are some screenshots of the license list index and exceptions index.

![Untitled](https://user-images.githubusercontent.com/378172/99140889-792d5d80-25fa-11eb-9cbf-a9d015c18f42.png)
![Untitled2](https://user-images.githubusercontent.com/378172/99140890-79c5f400-25fa-11eb-9d0d-72582b26cd64.png)

**Comment by swinslow** [comment]
+1 from me, thanks @goneall!

**Comment by goneall** [comment]
Resolved with PR #85
