### ISSUE TITLE
Invalid SPDX links for license information

### ISSUE THREAD

**Issue by kornefalk** [spdx/LicenseListPublisher#180]
The following links does not exist with the return code `HTTP/1.1 404 Not Found`

ERROR "https://spdx.org/licenses/Adobe-Display-PostScript.html"                                             
ERROR "https://spdx.org/licenses/AML-glslang.html"                                                   
ERROR "https://spdx.org/licenses/BSD-Source-beginning-file.html"                                                        
ERROR "https://spdx.org/licenses/BSD-Systemics-W3Works.html"                                             
ERROR "https://spdx.org/licenses/Caldera-no-preamble.html"                                                         
ERROR "https://spdx.org/licenses/CC-BY-3.0-AU.html"                                             
ERROR "https://spdx.org/licenses/DEC-3-Clause.html"                                                           
ERROR "https://spdx.org/licenses/DRL-1.1.html"                                                    
ERROR "https://spdx.org/licenses/FSFAP-no-warranty-disclaimer.html"                                             
ERROR "https://spdx.org/licenses/GCR-docs.html"                                              
ERROR "https://spdx.org/licenses/hdparm.html"                                                                       
ERROR "https://spdx.org/licenses/HPND-Kevlin-Henney.html"                                                
ERROR "https://spdx.org/licenses/HPND-MIT-disclaimer.html"                                             
ERROR "https://spdx.org/licenses/HPND-sell-MIT-disclaimer-xserver.html"                                             
ERROR "https://spdx.org/licenses/ISC-Veillard.html"                                                                 
ERROR "https://spdx.org/licenses/LPD-document.html"                                                                
ERROR "https://spdx.org/licenses/mailprio.html"                                                          
ERROR "https://spdx.org/licenses/Pixar.html"                                                                     
ERROR "https://spdx.org/licenses/radvd.html"                                                                     
ERROR "https://spdx.org/licenses/SAX-PD-2.0.html"                                             
ERROR "https://spdx.org/licenses/TGPPL-1.0.html"                                                  
ERROR "https://spdx.org/licenses/Unicode-3.0.html"                                               
ERROR "https://spdx.org/licenses/xkeyboard-config-Zinoviev.html"

**Comment by goneall** [comment]
I didn't do an exhaustive review, but it looks like at least some of these were added in version 3.23 of the SPDX license list.

The currently published version is 3.22.

This will be resolved once the new version is published.

I'll close this issue since it is not an issue for the publisher.

@kornefalk if there are any of the above which have a `listVersionAdded` < 3.23, please comment or add a new issue.

cc: @swinslow

**Comment by swinslow** [comment]
@kornefalk As @goneall mentioned, all of these appear to be licenses that will be officially published in the v3.23 release later today.

In the interim, prior to each official release, licenses that were merged should become immediately visible at the preview license list site at https://spdx.github.io/license-list-data/
