### ISSUE TITLE
Extra spaces are placed around optional text

### ISSUE THREAD

**Issue by goneall** [spdx/LicenseListPublisher#42]
When enclosing an optional character with `<optional>c</optional>`, spaces are added before and after the optional character when generating the canonical text.  This is problematic for some strings - e.g. `http<optional>s</optional>://www.gnu.org/licenses/` will produce `http s ://www.gnu.org/licenses/`.

See issue https://github.com/spdx/license-list-data/issues/42 for a list of files having this problem.

Due to the XML parsing, it will be difficult to determine if white space is desired before or after the optional tag.

**Comment by zvr** [comment]
Uh-oh... I created some `commit<optional>s<optional>`, `bring<optional>s</optional>`, etc. matches for strings last week... ;-)

**Comment by jhabdas** [comment]
nudge

**Comment by goneall** [comment]
Since XML allows white space before and after elements, I can not think of a way to solve this without modifying the license list XML schema.

Here's a proposal:

How about we add an attribute to `<optional>` in the license list XML "nospace".  It would have the following possible values:

- none: no spaces would be included before and after the optional value
- before: only a space before would be generated
- after: only a space after would be generated
- both: a space before and after the optional value would be generated

The default would be both (same behavior as today).

**Comment by zvr** [comment]
Surely with this interpretation of the values the attribute has to be named `space` instead of `nospace`.  😏 

Since the texts are also used for matching, the descriptions should talk about "white space" (not "a space") and use "generated/accepted" instead of "generated" (or "included").

👍 on the proposal

**Comment by bberberov** [comment]
Could you explain the problem?  I believe XSLT allows for collapsing elements, and existing space before and after would be preserved as written.

**Comment by goneall** [comment]
There are actually 2 problems - one is matching and one is generating the text based on the markup.  

This is generated in a Java tool - the code can be found at: https://github.com/spdx/LicenseListPublisher/tree/master/src/org/spdx/licenselistpublisher/licensegenerator

**Comment by bberberov** [comment]
Thanks.  i'll try and read the code.  It has been a while since I worked with Java.  I was mainly interested in generating accurate non-plain text versions of licenses for use in projects.

**Comment by bberberov** [comment]
I believe the issue is here:

https://github.com/spdx/LicenseListPublisher/blob/master/src/org/spdx/licensexml/LicenseXmlHelper.java#L308

To me this seems to always wrap `<optional>` in spaces.  If this can be modified to preserve whitespace as written, it should work.

**Comment by goneall** [comment]
The challenge is knowing whether to preserve the white space.  The XML parser strips out the white space between the tags so I don't think it is possible to know if the which space should be added or not.  We also don't have the original text to compare it to.

**Comment by goneall** [comment]
I'm implementing the "spacing" attribute for the optional element in the LicenseListXML schema.  As I was updating the code, I realized that the current behavior is adding a space before, not before and after, the optional text.  Based on this, I'll make the default "before".

You can review the PR for the schema change at https://github.com/spdx/license-list-XML/pull/889

**Comment by goneall** [comment]
The tools have been updated to implement the optional spacing, so I'm closing this PR.

We still need to go through the license-list-XML and update the optional text before closing the related license-list-data issue.
