### ISSUE TITLE
Create alternative or optional text for copyright text

### ISSUE THREAD

**Issue by goneall** [spdx/LicenseListPublisher#48]
Text enclosed by the copyright element are treated as normal text requiring complete matches.  It should be made either alternate or optional per matching guidelines section 2.1.3.

**Comment by goneall** [comment]
Code to be modified is near https://github.com/spdx/LicenseListPublisher/blob/518b9964fbe8b226c70d5aefe7e520a3a5b9186a/src/org/spdx/licensexml/LicenseXmlHelper.java#L145

**Comment by goneall** [comment]
This is related to https://github.com/spdx/license-list-XML/issues/866#issuecomment-497983940 and https://github.com/fsfe/reuse-docs/issues/16

**Comment by zvr** [comment]
simply put: `copyrightText` should be treated the same as `titleText` for matching.

**Comment by goneall** [comment]
Resolved in PR #54
