### ISSUE TITLE
Differences in sorting for the license list website indexes

### ISSUE THREAD

**Issue by swinslow** [spdx/LicenseListPublisher#56]
For the **main license list** (https://spdx.org/licenses/), the entries on the index are by default sorted alphabetically by the identifier, case-insensitive (which is correct).

For the **exceptions list** (https://spdx.org/licenses/exceptions-index.html), they are also sorted alphabetically by the identifier -- however, on this page the sorting is case-sensitive. Those beginning with lowercase letters (`eCos-exception-2.0` and thereafter) are all sorted at the end by default. Clicking on the "Identifier" column header causes them to sort into the correct, case-insensitive ordering.

Finally, for the **deprecated licenses list** (https://spdx.org/licenses/, at the bottom), I don't really see a pattern in the way they are sorted by default.

**Comment by swinslow** [comment]
For completeness, there is also a **deprecated exceptions list** (https://spdx.org/licenses/exceptions-index.html, at the bottom) but there is only one entry on it at present. So currently, it is sorted correctly.  :)

**Comment by goneall** [comment]
Resolved with PR #84
