### ISSUE TITLE
Optional color is not rendered for text inside a paragraph tag

### ISSUE THREAD

**Issue by goneall** [spdx/LicenseListPublisher#57]
The HTML for the license renders optional text in blue color.  This is currently done by generating a div with a class name of `optional-license-text`.  The [stylesheet ](https://github.com/spdx/LicenseListPublisher/blob/a8c187b8106ded3dcf0df33df92bd152f864a54a/resources/screen.css#L20)specifies a blue color for this class.  Paragraphs included within this div use the default paragraph color rather blue.

I think this is a straightforward fix for the stylesheet (e.g. add paragraph and any other formatting elements).

**Comment by goneall** [comment]
@swinslow - If you could take a look at the stylesheet and provide any pointers.

**Comment by zvr** [comment]
Looking, for example, at the Condor-1.1 license, the bottom part ("For more information") is `<optional>`.
It should appear in blue, BUT... it actually contains `<p>` elements and the `.page p` color overrides the color of optional.

Why is the `.page p` needed, since we already have the `.page` one?

**Comment by goneall** [comment]
Thanks @zvr for the analysis!

> Why is the .page p needed, since we already have the .page one?

Not sure - @jlovejoy do you know why we have these style edits?

I hacked the Condor-1.1 html on the website removing the `.page p`.  This fixed the issue.

I can remove this from the template and fix this permanently for the next revision of the license list.

A couple of questions:
- Should we remove the other `.page xx` items where the color is the same as `.page`?
- Should we move the inline style from the [template](https://github.com/spdx/LicenseListPublisher/blob/master/resources/htmlTemplate/LicenseHTMLTemplate.html) to the [.css file](https://github.com/spdx/LicenseListPublisher/blob/master/resources/screen.css)?

**Comment by goneall** [comment]
Based on a discussion with @swinslow and @jlovejoy , I'll try removing the `.page p` and `.page th` from the style embedded in the template.

We'll review on preview before committing the changes.

**Comment by goneall** [comment]
resolved with PR #58
