### ISSUE TITLE
Add a validity attribute to crossRef

### ISSUE THREAD

**Issue by ppalaga** [spdx/LicenseListPublisher#60]
This is a followup of https://github.com/spdx/license-list-XML/issues/780 where validity of http://www.microsoft.com/opensource/licenses.mspx was discussed.

It would be nice if the URLs known not to return valid content could be annotated accordingly.

For our particular use case an optional boolean attribute would be enough. The attribute name could be e.g. `valid` and it could default to `true`. The meaning of the values could be: 

`true`: At the time of releasing the given version of the SPDX license database, the URL returned (directly or via HTTP redirect) a document containing the text of the given license. This also includes the situation when the document contained the the text of the given license and a text of one of more other licenses. 

`false`: otherwise. (URL dead, URL redirecting to a document not containing the license text, etc.)

For JSON files where the URLs are currently just an array of strings, I propose the following: (1) the `seeAlso` attribute gets deprecated and will be kept unchanged for backwards compatibility; (2) a new attribute `crossRefs` will be added that will contain an array of `crossRef` objects having two attributes: `url` holding the URL and `valid` holding the validity status.

Before the change:

```
{
      "reference": "./Apache-2.0.html",
      "isDeprecatedLicenseId": false,
      "isFsfLibre": true,
      "detailsUrl": "http://spdx.org/licenses/Apache-2.0.json",
      "referenceNumber": "26",
      "name": "Apache License 2.0",
      "licenseId": "Apache-2.0",
      "seeAlso": [
        "http://www.apache.org/licenses/LICENSE-2.0",
        "https://opensource.org/licenses/Apache-2.0"
      ],
      "isOsiApproved": true
    }
```

After the change:

```
{
      "reference": "./Apache-2.0.html",
      "isDeprecatedLicenseId": false,
      "isFsfLibre": true,
      "detailsUrl": "http://spdx.org/licenses/Apache-2.0.json",
      "referenceNumber": "26",
      "name": "Apache License 2.0",
      "licenseId": "Apache-2.0",
      "seeAlso": [
        "http://www.apache.org/licenses/LICENSE-2.0",
        "https://opensource.org/licenses/Apache-2.0"
      ],
      "crossRefs": [
        {"url":"http://www.apache.org/licenses/LICENSE-2.0", "valid":"true"},
        {"url":"https://opensource.org/licenses/Apache-2.0", "valid":"true"}
      ],
      "isOsiApproved": true
    }
```

Motivation: 

We try to leverage SPDX license data in license-maven-plugin [1] for creating license reports. This i.a. includes downloading license texts from the URLs, assigning license names to those documents as well as grouping URLs that deliver the same content. Clearly, having documents in the report that actually do not contain any license text is a problem.

[1] https://github.com/mojohaus/license-maven-plugin

**Comment by zvr** [comment]
@goneall I"m sure you have already thought about it, but just to be sure: in order for a link to be "valid",  licenseListPublisher should check that it returns a page (not 404) _and_ that the content corresponds with the license in question. This means digging through the returned HTML of the page (if found), disregarding all decorations (e.g. logos, menus, archive.org frames, etc.), getting the text and comparing it...

**Comment by swinslow** [comment]
Great, thanks @goneall!

**Comment by goneall** [comment]
@zvr I wasn't planning on checking the text itself, but just recording dead links in some type of attribute on the license.

Perhaps we can separate this into 2 separate issues - one to add an attribute for dead links and a second issue for licenses that do not match.  Matching licenses would be a fun project, but it would be quite a bit of work.  Perhaps a summer of code student project?

**Comment by ppalaga** [comment]
> Matching licenses would be a fun project

+100! Having it would be really nice.

**Comment by goneall** [comment]
I just added a [GSoC project idea](https://wiki.spdx.org/view/GSOC/GSOC_ProjectIdeas#Validate_License_Cross-References).  @ppalaga feel free to update the proposal or suggest improvements.

**Comment by goneall** [comment]
The GSoC project is now completed and merged into the tool.  See PR #64, #67, #70, #71, and #74 

Closing this PR as resolved.

NOTE: This will not show up in the license-list data until the next release of the SPDX tools scheduled for the last week of November 2020.
