### ISSUE TITLE
Use HTTPS for URLs where possible

### ISSUE THREAD

**Issue by vlsi** [spdx/LicenseListPublisher#62]
For instance:

```
http://www.apache.org/licenses/LICENSE-2.0
...
http://spdx.org/licenses/Artistic-1.0-Perl.json
```

**Comment by zvr** [comment]
If this is for license texts, the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines) already say that `http:` and `https:` are equivalent.

**Comment by goneall** [comment]
The URL's show up in 2 places - in the license text and in the seeAlso URL's.

For the text, I agree with @zvr that the matching is already taken care of and I don't think we should be modifying the text of the license itself.

For the seeAlso there is a project already underway to validate and correct the license URL's.  

We can use this issue to track the seeAlso usage (although I think there may be another issue out that that may be a duplicate).

**Comment by goneall** [comment]
This issue should now be resolved with the new cross-refs work complete (see the [CrossRef class](https://github.com/spdx/Spdx-Java-Library/blob/master/src/main/java/org/spdx/library/model/license/CrossRef.java) for implementation details).  If there is any issue with the cross-refs implementation, please open a new issue.
