### ISSUE TITLE
License details should include a link to the plain text, if known

### ISSUE THREAD

**Issue by sschuberth** [spdx/LicenseListPublisher#78]
Unfortunately, the formatting in the `licenseText`'s JSON value is broken for a lot of licenses (e.g. regarding indentation and paragraphs). For any processing the plain text version of the license text, if provided by upstream, should be the source of truth. To capture that, I propose to include a link to the plain text version, if any, into the license details. Preferably this would go to a new `plainTextUrl` field, but better than nothing would also be a convention that the first link in `seeAlso` refers to the plain text version, if any.

Also, if a link to an upstream plain text version exists, that plain text should be used as-is for the `licenseText` field, instead of creating its value by stripping formatting from some rich text version of the license text, as it seems to be done now.

**Comment by goneall** [comment]
PR #83 implements approach 1. above.

**Comment by sschuberth** [comment]
I'm reopening this to remind myself that the issue hasn't really been fixed yet. While PR #83 laid the foundation for *getting* it fixed, https://github.com/spdx/license-list-data/blob/master/text/Apache-2.0.txt still does not match https://www.apache.org/licenses/LICENSE-2.0.txt formatting-wise.

IIUC @goneall correctly, the remaining thing to do is to commit the original / upstream plain text licenses to https://github.com/spdx/license-list-XML/tree/master/test/simpleTestForGenerator and then rerun this publisher to make the correct licenses show up at https://github.com/spdx/license-list-data/tree/master/text. I'll try to wrote a script for that to finally resolve this long-stand issue.

**Comment by sschuberth** [comment]
And actually, this specific issue is about *tracking* the original URL to the original plain text licenses as part of license metadata. That is, at the example of `Apache-2.0` we should track that the plain text version of the license is available at https://www.apache.org/licenses/LICENSE-2.0.txt, but we track only the HTML version at https://www.apache.org/licenses/LICENSE-2.0.

So, fixing the other issue #30 that I've reopening will *not* automatically fix this issue.

**Comment by sschuberth** [comment]
I'm closing this as a duplicate of https://github.com/spdx/LicenseListPublisher/issues/30.
