### ISSUE TITLE
"See also" priority number

### ISSUE THREAD

**Issue by wonkydonky** [spdx/LicenseListPublisher#79]
Licenses have a property called "see also". As far as I understand this is used to link to external resources, such as the official webpage. If there are more than one link, there should be a priority number to indicate which link is preferred. For example GPL-3.0-only has `http://www.opensource.org/licenses/GPL-3.0` and `http://www.gnu.org/licenses/gpl-3.0-standalone.html`. The GNU link should be given a higher priority.

**Comment by goneall** [comment]
PR #82 now preserves the order of the SeeAlso URL's which can provide a priority.  The order in which the seeAlso URL's are added in the XML will be the order in which they will be displayed on the website.

**Comment by goneall** [comment]
Note: There is now an `order` property in the `CrossRef` class which can be used as a priority - it is defined to be the order in which the seeAlso was found in the License XML document.
