### ISSUE TITLE
AGPL (or later)

### ISSUE THREAD

**Issue by kkmzero** [spdx/LicenseListPublisher#81]
What exactly is the difference between these two license templates? I checked them and they seem identical, however I would expect AGPL-3.0-only to not have "or any later version" line.

https://github.com/spdx/license-list-data/blob/master/text/AGPL-3.0-or-later.txt
https://github.com/spdx/license-list-data/blob/master/text/AGPL-3.0-only.txt

**Comment by goneall** [comment]
@kkmzero There is no difference between the templates.  The templates are for the actual license text which is identical between the 2 licenses.  The license header may be different, however.

The source used to generate the license data is https://github.com/spdx/license-list-XML/blob/master/src/AGPL-3.0-or-later.xml and https://github.com/spdx/license-list-XML/blob/master/src/AGPL-3.0-only.xml

The Notes field describes the difference a bit more.

BTW - the same approach is used for other "-only" and "-or-later" licenses.
