### ISSUE TITLE
Reporting "no longer live" where link is a valid redirect

### ISSUE THREAD

**Issue by swinslow** [spdx/LicenseListPublisher#92]
Hi @goneall -- I'm not sure if this is the right repo to report this in, so let me know if it should go elsewhere  :)

In looking at the latest License List release, I'm noticing that several links are deactivated and listed as "no longer live" even though they do actually lead to a valid webpage. It looks like it's happening in particular where the link is a valid redirect, rather than being the final page itself.

A few examples:
* [Artistic-1.0-Perl](https://spdx.org/licenses/Artistic-1.0-Perl.html): http://dev.perl.org/licenses/artistic.html is listed as "no longer live", though visiting it redirects to https://dev.perl.org/licenses/artistic.html (same site but with http => https)
* [Artistic-2.0](https://spdx.org/licenses/Artistic-2.0.html): http://www.perlfoundation.org/artistic_license_2_0 is listed as "no longer live", though visiting it redirects to https://www.perlfoundation.org/artistic-license-20.html
* [BitTorrent-1.1](https://spdx.org/licenses/BitTorrent-1.1.html): http://directory.fsf.org/wiki/License:BitTorrentOSL1.1 is listed as "no longer live", though visiting it redirects to https://directory.fsf.org/wiki/License:BitTorrent-1.1

This might be something that the GSoC student who originally wrote the link validation code might be able to take a look at?

**Comment by goneall** [comment]
@swinslow Yes - this is the right repo and it would involve the link validation.  I need to check the code, but I'm guessing it is taking the redirect as a cause for the link to not be live.  I'll look into it later this week.

Thanks for pointing this out.

**Comment by goneall** [comment]
@tjasmith Let me know if you have any thoughts on this issue.

**Comment by goneall** [comment]
This is resolved with commit 90b49dadb889ec7ce611990bdc839a87e226072a
